// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwiqicyfwvwwgqbxhmvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aXFpY3lmd3Z3d2dxYnhobXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODg2NzUsImV4cCI6MjA1NzQ2NDY3NX0.y862wSmbJoMnApF0lPwr4x828w4hzwLc-QfHem26lok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);